### ISSUE TITLE
bcrypt fails on installation

### ISSUE THREAD

**Issue by swetoast** [roastlechon/nodejs-rtorrent#53]
18536 verbose about to build /home/osmc/node_modules/nodejs-rtorrent
18537 verbose unlock done using /root/.npm/_locks/nodejs-rtorrent-8d77a7a5c5a24464.lock for /home/osmc/node_modules/nodejs-rtorrent
18538 verbose stack Error: bcrypt@0.7.8 install: `node-gyp rebuild`
18538 verbose stack Exit status 1
18538 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
18538 verbose stack     at EventEmitter.emit (events.js:110:17)
18538 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
18538 verbose stack     at ChildProcess.emit (events.js:110:17)
18538 verbose stack     at maybeClose (child_process.js:1008:16)
18538 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
18539 verbose pkgid bcrypt@0.7.8
18540 verbose cwd /home/osmc
18541 error Linux 4.1.3-2-osmc
18542 error argv "node" "/usr/local/bin/npm" "install" "https://github.com/roastlechon/nodejs-rtorrent"
18543 error node v0.12.1
18544 error npm  v2.14.0
18545 error code ELIFECYCLE
18546 error bcrypt@0.7.8 install: `node-gyp rebuild`
18546 error Exit status 1
18547 error Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
18547 error This is most likely a problem with the bcrypt package,
18547 error not with npm itself.
18547 error Tell the author that this fails on your system:
18547 error     node-gyp rebuild
18547 error You can get their info via:
18547 error     npm owner ls bcrypt
18547 error There is likely additional logging output above.
18548 verbose exit [ 1, true ]
18549 verbose unbuild node_modules/nodejs-rtorrent/node_modules/bcrypt
18550 info preuninstall bcrypt@0.7.8
18551 info uninstall bcrypt@0.7.8
18552 verbose unbuild rmStuff bcrypt@0.7.8 from /home/osmc/node_modules
18553 verbose unbuild rmStuff in /home/osmc/node_modules/nodejs-rtorrent/node_modules
18554 info postuninstall bcrypt@0.7.8
18555 silly gentlyRm /home/osmc/node_modules/nodejs-rtorrent/node_modules/bcrypt is being purged from base /home/osmc
18556 verbose gentlyRm don't care about contents; nuking /home/osmc/node_modules/nodejs-rtorrent/node_modules/bcrypt
18557 silly vacuum-fs purging /home/osmc/node_modules/nodejs-rtorrent/node_modules/bcrypt
18558 silly vacuum-fs quitting because other entries in /home/osmc/node_modules/nodejs-rtorrent/node_modules
18559 verbose unbuild node_modules/nodejs-rtorrent
18560 info preuninstall nodejs-rtorrent@0.0.28
18561 info uninstall nodejs-rtorrent@0.0.28
18562 verbose unbuild rmStuff nodejs-rtorrent@0.0.28 from /home/osmc/node_modules
18563 info postuninstall nodejs-rtorrent@0.0.28
18564 silly gentlyRm /home/osmc/node_modules/nodejs-rtorrent is being purged from base /home/osmc
18565 verbose gentlyRm don't care about contents; nuking /home/osmc/node_modules/nodejs-rtorrent
18566 silly vacuum-fs purging /home/osmc/node_modules/nodejs-rtorrent
18567 silly vacuum-fs quitting because other entries in /home/osmc/node_modules

**Comment by swetoast** [comment]
My plan is to use the webui for rtorrent and include them as a package for OSMC Appstore

For more complete logs:
Shell output: http://paste.osmc.io/pozikemobe.pl
Debug log: http://paste.osmc.io/iguqurafuj

**Comment by swetoast** [comment]
finally got it to compile but it still fails

info: Connect to rtorrent via scgi
info: Initializing nodejs-rtorrent server.
/home/osmc/nodejs-rtorrent/node_modules/bcrypt/node_modules/bindings/bindings.js:87
  throw err
        ^
Error: Could not load the bindings file. Tried:
 → /home/osmc/nodejs-rtorrent/node_modules/bcrypt/build/bcrypt_lib.node
 → /home/osmc/nodejs-rtorrent/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /home/osmc/nodejs-rtorrent/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /home/osmc/nodejs-rtorrent/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /home/osmc/nodejs-rtorrent/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /home/osmc/nodejs-rtorrent/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /home/osmc/nodejs-rtorrent/node_modules/bcrypt/Release/bcrypt_lib.node
 → /home/osmc/nodejs-rtorrent/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /home/osmc/nodejs-rtorrent/node_modules/bcrypt/compiled/0.12.1/linux/arm/bcrypt_lib.node
    at bindings (/home/osmc/nodejs-rtorrent/node_modules/bcrypt/node_modules/bindings/bindings.js:84:13)
    at Object.<anonymous> (/home/osmc/nodejs-rtorrent/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/osmc/nodejs-rtorrent/src/node/models/schemas/user.js:3:14)
    at Module._compile (module.js:460:26)

**Comment by roastlechon** [comment]
It's possible your bcrypt hasn't been installed correctly still. What OS
are you running and version of nodejs and npm?

**Comment by swetoast** [comment]
npm: 2.14.0
node: v0.12.1

OS: OSMC (www.osmv.tv)

wanted to use this webui instead of a full blown webserver for a app package as an alternative for transmission
